on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: 1.43.3
      - name: "Run tests."
        run: deno test
